### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by yuchiko** [KapSSe/site-jwood#1]
1) http://joxi.ru/MAjpx91f4X39Qm
2) Что-то пошло не так, зря ты к width привязался http://joxi.ru/DmBxM0Nuw1kaNA
3) а чего такое большое ? http://joxi.ru/82QqxNYCjqaow2
4) а где плавность в скролле?
5) Учитывай, что я на своих 1200px уже должен видеть красивый сайт, не надо под HD всех ровнять http://joxi.ru/5mdQa37SkZQWq2
6) http://joxi.ru/GrqyJ9LCQJl9jr
7) Мне не нравится, что ты тут дублируешь, вместо того, чтобы оббернуть их одним 
```
<a href="#about" class="scroll_down_item scr_text to_uppercase text_white">scroll down to see more</a>
            <a href="#about" class="scroll_down_item to_uppercase text_white"><img src="img/arrow.png" alt=""></a>
```
8) Бага с адаптивом 767px  http://joxi.ru/VrwM69qfOJGEN2

**Comment by KapSSe** [comment]
Поправил,глянь как сможешь.
